// source: spire/api/types/jwtsvid.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var spire_api_types_spiffeid_pb = require('../../../spire/api/types/spiffeid_pb.js');
goog.object.extend(proto, spire_api_types_spiffeid_pb);
goog.exportSymbol('proto.spire.api.types.JWTSVID', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.spire.api.types.JWTSVID = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.spire.api.types.JWTSVID, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.spire.api.types.JWTSVID.displayName = 'proto.spire.api.types.JWTSVID';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.spire.api.types.JWTSVID.prototype.toObject = function(opt_includeInstance) {
  return proto.spire.api.types.JWTSVID.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.spire.api.types.JWTSVID} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.spire.api.types.JWTSVID.toObject = function(includeInstance, msg) {
  var f, obj = {
    token: jspb.Message.getFieldWithDefault(msg, 1, ""),
    id: (f = msg.getId()) && spire_api_types_spiffeid_pb.SPIFFEID.toObject(includeInstance, f),
    expiresAt: jspb.Message.getFieldWithDefault(msg, 3, 0),
    issuedAt: jspb.Message.getFieldWithDefault(msg, 4, 0),
    hint: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.spire.api.types.JWTSVID}
 */
proto.spire.api.types.JWTSVID.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.spire.api.types.JWTSVID;
  return proto.spire.api.types.JWTSVID.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.spire.api.types.JWTSVID} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.spire.api.types.JWTSVID}
 */
proto.spire.api.types.JWTSVID.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setToken(value);
      break;
    case 2:
      var value = new spire_api_types_spiffeid_pb.SPIFFEID;
      reader.readMessage(value,spire_api_types_spiffeid_pb.SPIFFEID.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setExpiresAt(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setIssuedAt(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setHint(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.spire.api.types.JWTSVID.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.spire.api.types.JWTSVID.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.spire.api.types.JWTSVID} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.spire.api.types.JWTSVID.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getToken();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      spire_api_types_spiffeid_pb.SPIFFEID.serializeBinaryToWriter
    );
  }
  f = message.getExpiresAt();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getIssuedAt();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getHint();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string token = 1;
 * @return {string}
 */
proto.spire.api.types.JWTSVID.prototype.getToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.spire.api.types.JWTSVID} returns this
 */
proto.spire.api.types.JWTSVID.prototype.setToken = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional SPIFFEID id = 2;
 * @return {?proto.spire.api.types.SPIFFEID}
 */
proto.spire.api.types.JWTSVID.prototype.getId = function() {
  return /** @type{?proto.spire.api.types.SPIFFEID} */ (
    jspb.Message.getWrapperField(this, spire_api_types_spiffeid_pb.SPIFFEID, 2));
};


/**
 * @param {?proto.spire.api.types.SPIFFEID|undefined} value
 * @return {!proto.spire.api.types.JWTSVID} returns this
*/
proto.spire.api.types.JWTSVID.prototype.setId = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.spire.api.types.JWTSVID} returns this
 */
proto.spire.api.types.JWTSVID.prototype.clearId = function() {
  return this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.spire.api.types.JWTSVID.prototype.hasId = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int64 expires_at = 3;
 * @return {number}
 */
proto.spire.api.types.JWTSVID.prototype.getExpiresAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.spire.api.types.JWTSVID} returns this
 */
proto.spire.api.types.JWTSVID.prototype.setExpiresAt = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int64 issued_at = 4;
 * @return {number}
 */
proto.spire.api.types.JWTSVID.prototype.getIssuedAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.spire.api.types.JWTSVID} returns this
 */
proto.spire.api.types.JWTSVID.prototype.setIssuedAt = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string hint = 5;
 * @return {string}
 */
proto.spire.api.types.JWTSVID.prototype.getHint = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.spire.api.types.JWTSVID} returns this
 */
proto.spire.api.types.JWTSVID.prototype.setHint = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


goog.object.extend(exports, proto.spire.api.types);
