// source: spire/api/types/selector.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

goog.exportSymbol('proto.spire.api.types.Selector', null, global);
goog.exportSymbol('proto.spire.api.types.SelectorMatch', null, global);
goog.exportSymbol('proto.spire.api.types.SelectorMatch.MatchBehavior', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.spire.api.types.Selector = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.spire.api.types.Selector, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.spire.api.types.Selector.displayName = 'proto.spire.api.types.Selector';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.spire.api.types.SelectorMatch = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.spire.api.types.SelectorMatch.repeatedFields_, null);
};
goog.inherits(proto.spire.api.types.SelectorMatch, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.spire.api.types.SelectorMatch.displayName = 'proto.spire.api.types.SelectorMatch';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.spire.api.types.Selector.prototype.toObject = function(opt_includeInstance) {
  return proto.spire.api.types.Selector.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.spire.api.types.Selector} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.spire.api.types.Selector.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, ""),
    value: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.spire.api.types.Selector}
 */
proto.spire.api.types.Selector.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.spire.api.types.Selector;
  return proto.spire.api.types.Selector.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.spire.api.types.Selector} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.spire.api.types.Selector}
 */
proto.spire.api.types.Selector.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.spire.api.types.Selector.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.spire.api.types.Selector.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.spire.api.types.Selector} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.spire.api.types.Selector.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getValue();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string type = 1;
 * @return {string}
 */
proto.spire.api.types.Selector.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.spire.api.types.Selector} returns this
 */
proto.spire.api.types.Selector.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string value = 2;
 * @return {string}
 */
proto.spire.api.types.Selector.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.spire.api.types.Selector} returns this
 */
proto.spire.api.types.Selector.prototype.setValue = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.spire.api.types.SelectorMatch.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.spire.api.types.SelectorMatch.prototype.toObject = function(opt_includeInstance) {
  return proto.spire.api.types.SelectorMatch.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.spire.api.types.SelectorMatch} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.spire.api.types.SelectorMatch.toObject = function(includeInstance, msg) {
  var f, obj = {
    selectorsList: jspb.Message.toObjectList(msg.getSelectorsList(),
    proto.spire.api.types.Selector.toObject, includeInstance),
    match: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.spire.api.types.SelectorMatch}
 */
proto.spire.api.types.SelectorMatch.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.spire.api.types.SelectorMatch;
  return proto.spire.api.types.SelectorMatch.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.spire.api.types.SelectorMatch} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.spire.api.types.SelectorMatch}
 */
proto.spire.api.types.SelectorMatch.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.spire.api.types.Selector;
      reader.readMessage(value,proto.spire.api.types.Selector.deserializeBinaryFromReader);
      msg.addSelectors(value);
      break;
    case 2:
      var value = /** @type {!proto.spire.api.types.SelectorMatch.MatchBehavior} */ (reader.readEnum());
      msg.setMatch(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.spire.api.types.SelectorMatch.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.spire.api.types.SelectorMatch.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.spire.api.types.SelectorMatch} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.spire.api.types.SelectorMatch.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSelectorsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.spire.api.types.Selector.serializeBinaryToWriter
    );
  }
  f = message.getMatch();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.spire.api.types.SelectorMatch.MatchBehavior = {
  MATCH_EXACT: 0,
  MATCH_SUBSET: 1,
  MATCH_SUPERSET: 2,
  MATCH_ANY: 3
};

/**
 * repeated Selector selectors = 1;
 * @return {!Array<!proto.spire.api.types.Selector>}
 */
proto.spire.api.types.SelectorMatch.prototype.getSelectorsList = function() {
  return /** @type{!Array<!proto.spire.api.types.Selector>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.spire.api.types.Selector, 1));
};


/**
 * @param {!Array<!proto.spire.api.types.Selector>} value
 * @return {!proto.spire.api.types.SelectorMatch} returns this
*/
proto.spire.api.types.SelectorMatch.prototype.setSelectorsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.spire.api.types.Selector=} opt_value
 * @param {number=} opt_index
 * @return {!proto.spire.api.types.Selector}
 */
proto.spire.api.types.SelectorMatch.prototype.addSelectors = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.spire.api.types.Selector, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.spire.api.types.SelectorMatch} returns this
 */
proto.spire.api.types.SelectorMatch.prototype.clearSelectorsList = function() {
  return this.setSelectorsList([]);
};


/**
 * optional MatchBehavior match = 2;
 * @return {!proto.spire.api.types.SelectorMatch.MatchBehavior}
 */
proto.spire.api.types.SelectorMatch.prototype.getMatch = function() {
  return /** @type {!proto.spire.api.types.SelectorMatch.MatchBehavior} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.spire.api.types.SelectorMatch.MatchBehavior} value
 * @return {!proto.spire.api.types.SelectorMatch} returns this
 */
proto.spire.api.types.SelectorMatch.prototype.setMatch = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


goog.object.extend(exports, proto.spire.api.types);
