// source: spire/api/types/x509svid.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var spire_api_types_spiffeid_pb = require('../../../spire/api/types/spiffeid_pb.js');
goog.object.extend(proto, spire_api_types_spiffeid_pb);
goog.exportSymbol('proto.spire.api.types.X509SVID', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.spire.api.types.X509SVID = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.spire.api.types.X509SVID.repeatedFields_, null);
};
goog.inherits(proto.spire.api.types.X509SVID, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.spire.api.types.X509SVID.displayName = 'proto.spire.api.types.X509SVID';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.spire.api.types.X509SVID.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.spire.api.types.X509SVID.prototype.toObject = function(opt_includeInstance) {
  return proto.spire.api.types.X509SVID.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.spire.api.types.X509SVID} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.spire.api.types.X509SVID.toObject = function(includeInstance, msg) {
  var f, obj = {
    certChainList: msg.getCertChainList_asB64(),
    id: (f = msg.getId()) && spire_api_types_spiffeid_pb.SPIFFEID.toObject(includeInstance, f),
    expiresAt: jspb.Message.getFieldWithDefault(msg, 3, 0),
    hint: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.spire.api.types.X509SVID}
 */
proto.spire.api.types.X509SVID.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.spire.api.types.X509SVID;
  return proto.spire.api.types.X509SVID.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.spire.api.types.X509SVID} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.spire.api.types.X509SVID}
 */
proto.spire.api.types.X509SVID.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.addCertChain(value);
      break;
    case 2:
      var value = new spire_api_types_spiffeid_pb.SPIFFEID;
      reader.readMessage(value,spire_api_types_spiffeid_pb.SPIFFEID.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setExpiresAt(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setHint(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.spire.api.types.X509SVID.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.spire.api.types.X509SVID.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.spire.api.types.X509SVID} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.spire.api.types.X509SVID.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCertChainList_asU8();
  if (f.length > 0) {
    writer.writeRepeatedBytes(
      1,
      f
    );
  }
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      spire_api_types_spiffeid_pb.SPIFFEID.serializeBinaryToWriter
    );
  }
  f = message.getExpiresAt();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getHint();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * repeated bytes cert_chain = 1;
 * @return {!(Array<!Uint8Array>|Array<string>)}
 */
proto.spire.api.types.X509SVID.prototype.getCertChainList = function() {
  return /** @type {!(Array<!Uint8Array>|Array<string>)} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * repeated bytes cert_chain = 1;
 * This is a type-conversion wrapper around `getCertChainList()`
 * @return {!Array<string>}
 */
proto.spire.api.types.X509SVID.prototype.getCertChainList_asB64 = function() {
  return /** @type {!Array<string>} */ (jspb.Message.bytesListAsB64(
      this.getCertChainList()));
};


/**
 * repeated bytes cert_chain = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getCertChainList()`
 * @return {!Array<!Uint8Array>}
 */
proto.spire.api.types.X509SVID.prototype.getCertChainList_asU8 = function() {
  return /** @type {!Array<!Uint8Array>} */ (jspb.Message.bytesListAsU8(
      this.getCertChainList()));
};


/**
 * @param {!(Array<!Uint8Array>|Array<string>)} value
 * @return {!proto.spire.api.types.X509SVID} returns this
 */
proto.spire.api.types.X509SVID.prototype.setCertChainList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {!(string|Uint8Array)} value
 * @param {number=} opt_index
 * @return {!proto.spire.api.types.X509SVID} returns this
 */
proto.spire.api.types.X509SVID.prototype.addCertChain = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.spire.api.types.X509SVID} returns this
 */
proto.spire.api.types.X509SVID.prototype.clearCertChainList = function() {
  return this.setCertChainList([]);
};


/**
 * optional SPIFFEID id = 2;
 * @return {?proto.spire.api.types.SPIFFEID}
 */
proto.spire.api.types.X509SVID.prototype.getId = function() {
  return /** @type{?proto.spire.api.types.SPIFFEID} */ (
    jspb.Message.getWrapperField(this, spire_api_types_spiffeid_pb.SPIFFEID, 2));
};


/**
 * @param {?proto.spire.api.types.SPIFFEID|undefined} value
 * @return {!proto.spire.api.types.X509SVID} returns this
*/
proto.spire.api.types.X509SVID.prototype.setId = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.spire.api.types.X509SVID} returns this
 */
proto.spire.api.types.X509SVID.prototype.clearId = function() {
  return this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.spire.api.types.X509SVID.prototype.hasId = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int64 expires_at = 3;
 * @return {number}
 */
proto.spire.api.types.X509SVID.prototype.getExpiresAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.spire.api.types.X509SVID} returns this
 */
proto.spire.api.types.X509SVID.prototype.setExpiresAt = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string hint = 4;
 * @return {string}
 */
proto.spire.api.types.X509SVID.prototype.getHint = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.spire.api.types.X509SVID} returns this
 */
proto.spire.api.types.X509SVID.prototype.setHint = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


goog.object.extend(exports, proto.spire.api.types);
