volumes:
  spire-agent-public:
  spire-server-public:
  spire-server-private:
  spire-agent-private:
services:
  spire-server:
    image: ghcr.io/spiffe/spire-server:1.8.2
    volumes:
      - ./spire/data/server:/run/spire/server/data
      - ./spire/config/docker:/run/spire/server/conf
      - ./spire/ca:/run/spire/server/conf/ca
      - /tmp/spire-server-private:/run/spire/server/private:rw
    command: ["-config", "/run/spire/server/conf/server.conf"]
    ports:
      - 8081:8081
      - 8090:8080
  spire-agent:
    pid: "host"
    image: ghcr.io/spiffe/spire-agent:1.8.2
    volumes:
      - ./spire/data/agent:/run/spire/agent/data
      - ./spire/config/docker:/run/spire/agent/conf
      - ./spire/ca:/run/spire/agent/conf/ca
      - /tmp/spire-agent-public:/run/spire/agent/public:rw
      - /tmp/spire-agent-private:/run/spire/agent/private:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
    command: [ "-config", "/run/spire/agent/conf/agent.conf", "-allowUnauthenticatedVerifiers" ]
    ports:
      - 8082:8081
      - 8091:8080
    depends_on:
      spire-server:
        condition: service_started
    labels:
      spiffe_id: spiffe://server.fs.com/workload/demo-public
  oidc:
    pid: "host"
    user: "1000:1000"
    image: fs/spiffe-oidc:latest
    volumes:
      - /tmp/spire-agent-public:/run/spire/public:rw
      - /tmp/spire-agent-private:/run/spire/private:rw
    environment:
      - WORKLOAD_SPIRE_ENDPOINT=unix:///run/spire/public/workload_api.sock
      - DELEGATED_ID_SPIRE_ENDPOINT=unix:///run/spire/private/admin_api.sock
      - ADMIN_SPIRE_ENDPOINT=spire-server:8081
      - ADMIN_SPIFFE_ID=spiffe://server.fs.com/workload/oidc-admin
      - PARENT_SPIFFE_ID=spiffe://server.fs.com/workload/oidc-admin
      - LOG_LEVEL=DEBUG
    ports:
      - 3000:3000
    depends_on:
      spire-agent:
        condition: service_started
    labels:
      spiffe_id: spiffe://server.fs.com/workload/oidc-admin
  workload-demo-service:
    pid: "host"
    image: fs/demo-service:latest
    volumes:
      - /tmp/spire-agent-public:/run/spire/public:rw
      - /tmp/spire-agent-private:/run/spire/private:rw
    environment:
      - WORKLOAD_ENDPOINT=unix:///run/spire/public/workload_api.sock
      - SPIFFE_ID=spiffe://server.fs.com/workload/demo-service
      - LOG_LEVEL=DEBUG
      - NODE_DEBUG=http

    depends_on:
      oidc:
        condition: service_started
    labels:
      spiffe_id: spiffe://server.fs.com/workload/demo-service
  workload-envoy:
    pid: "host"
    hostname: demo-service
    image: envoyproxy/envoy:v1.27.1
    environment:
      - SPIFFE_ID=spiffe://server.fs.com/workload/demo-service
    volumes:
      - /tmp/spire-agent-public:/run/spire/public:rw
      - ./spire/config/docker/envoy:/etc/envoy
      - ./spire/envoy:/tmp/envoy:rw
    ports:
      - 3020:3020 #mtls port
      - 9901:9901 #admin port
    depends_on:
      workload-demo-service:
        condition: service_started
      spire-agent:
        condition: service_started
    labels:
      spiffe_id: spiffe://server.fs.com/workload/demo-service
    command: ["-l", "debug", "--local-address-ip-version", "v4", "-c", "/etc/envoy/envoy.yaml", "--base-id", "2"]
  workload-demo-public:
    hostname: demo-public
    pid: "host"
    image: fs/workload-public:latest
    volumes:
      - /tmp/spire-agent-public:/run/spire/public:rw
      - /tmp/spire-agent-private:/run/spire/private:rw
    environment:
      - WORKLOAD_ENDPOINT=unix:///run/spire/public/workload_api.sock
      - SPIFFE_ID=spiffe://server.fs.com/workload/demo-public
      - LOG_LEVEL=DEBUG
      - NODE_DEBUG=http
      - SERVICE_ENDPOINT=https://demo-service:3020
    ports:
      - 3001:3001
    depends_on:
      oidc:
        condition: service_started
    labels:
      spiffe_id: spiffe://server.fs.com/workload/demo-public
